(** JPEG marker code values. *)

open! Base

val sof0 : int
val sof1 : int
val sof2 : int
val sof3 : int
val sof5 : int
val sof6 : int
val sof7 : int
val jpg : int
val sof9 : int
val sof10 : int
val sof11 : int
val sof13 : int
val sof14 : int
val sof15 : int
val dht : int
val dac : int
val rst0 : int
val rst1 : int
val rst2 : int
val rst3 : int
val rst4 : int
val rst5 : int
val rst6 : int
val rst7 : int
val soi : int
val eoi : int
val sos : int
val dqt : int
val dnl : int
val dri : int
val dhp : int
val exp : int
val app0 : int
val app1 : int
val app2 : int
val app3 : int
val app4 : int
val app5 : int
val app6 : int
val app7 : int
val app8 : int
val app9 : int
val app10 : int
val app11 : int
val app12 : int
val app13 : int
val app14 : int
val app15 : int
val jpg0 : int
val jpg13 : int
val com : int
val tem : int
val error : int
